"""empty message

Revision ID: 3687b5fed251
Revises:
Create Date: 2018-10-31 12:19:33.251338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3687b5fed251'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('test_property', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task') as batch_op:
        batch_op.drop_column('test_property')
    # ### end Alembic commands ###
