"""empty message

Revision ID: 86f640e62cd5
Revises: 3687b5fed251
Create Date: 2018-10-31 12:20:42.613106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86f640e62cd5'
down_revision = '3687b5fed251'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task') as batch_op:
        batch_op.drop_column('test_property')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('test_property', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
